### ISSUE TITLE
customers make mistakes all the time. should we have a page on how to delete and start from scratch?

### ISSUE THREAD

**Issue by alberttwong** [openshift-labs/starter-guides#20]
maybe give them a script or a list of objects they need to delete to reset the module?

**Comment by thoraxe** [comment]
I don't like this idea -- mostly because I use students making mistakes as an opportunity to fix what they broke publicly in front of everyone else. This provides an additional learning/training opportunity and also shows how easy it is to troubleshoot and recover from problems in OpenShift.

If a student gets so hosed that they need to start completely over, it means the leader is not checking in frequently enough with students to see if they're having problems!

**Comment by alberttwong** [comment]
Well... I don't think they see it has easy to go and delete routes, services, deployment, secrets and finally pod.   Yet again, this is the feedback.
